### ISSUE TITLE
Hardware acceleration is enabled by default?

### ISSUE THREAD

**Issue by alanrubin** [anvaka/panzoom#137] opened 2019-10-30 10:01 UTC
Hi,

I was wondering if hardware acceleration of all transformations is enabled by default? I see that for the DOM, you are using style.transform = 'matrix(....)', does that make CSS do hardware acceleration enabled already?

I'm asking because we are experiencing issues where panning and zooming of big images flashes repeatedly on large screen devices, I was wondering if that can be improved by hardware acceleration.

Thank you for this great library!

**Comment by dota2Pro** [comment] 2019-11-05 16:48
Attach JSfiddle where its reproducible, browser version, OS etc. Its probably due to lack of memory if you load big images on large screen devices

**Comment by anvaka** [comment] 2020-04-18 06:05
Resolving as there is no input. I've recently seen a similar issue here: https://github.com/anvaka/panzoom/issues/184 - was caused by transition animation on css - might be worth checking.

@alanrubin please feel free to re-open if you have a different cause and, like @dota2Pro suggested - please add a link to the page where we can reproduce it.

**Closed by anvaka** 2020-04-18 06:05 UTC
